let products = [
  {
    id: 1,
    name: "Amrut Fusion Single Malt",
    brand: "Amrut",
    quantity: "1",
    category: "Whisky",
    subCategory: "Indian Single Malt",
    country: "India",
    abv: "50%",
    volume: "750 ml",
    price: 4200,
    currency: "INR",
    rating: 4.6,
    reviewCount: 842,
    description:
      "Premium Indian single malt whisky with tropical fruit, spice and oak notes.",
    thumbnail: "https://i.pinimg.com/736x/7a/f8/a4/7af8a4702ac5ad3a888570d0374ccf2b.jpg",
    images: ["https://i.pinimg.com/736x/7a/f8/a4/7af8a4702ac5ad3a888570d0374ccf2b.jpg"],
    inStock: true,
    stock: 35,
    featured: true,
    flavours: ["Oak", "Fruit", "Spice"],
  },
  {
    id: 2,
    name: "Old Monk Supreme",
    brand: "Old Monk",
    quantity: "1",
    category: "Rum",
    subCategory: "Dark Rum",
    country: "India",
    abv: "42.8%",
    volume: "750 ml",
    price: 900,
    currency: "INR",
    rating: 4.5,
    reviewCount: 2150,
    description:
      "Classic Indian dark rum with caramel sweetness and vanilla aroma.",
    thumbnail: "https://i.pinimg.com/736x/a9/76/12/a97612272bdbfdee784169c5e7770dc4.jpg",
    images: ["https://i.pinimg.com/736x/a9/76/12/a97612272bdbfdee784169c5e7770dc4.jpg"],
    inStock: true,
    stock: 120,
    featured: false,
    flavours: ["Caramel", "Vanilla", "Molasses"],
  },
  {
    id: 3,
    name: "Paul John Brilliance",
    brand: "Paul John",
    quantity: "1",
    category: "Whisky",
    subCategory: "Single Malt",
    country: "India",
    abv: "46%",
    volume: "750 ml",
    price: 3500,
    currency: "INR",
    rating: 4.7,
    reviewCount: 620,
    description:
      "Goan single malt whisky matured in tropical conditions with honey notes.",
    thumbnail: "https://i.pinimg.com/736x/66/37/08/663708a0381ccb2c41064b20004aadd1.jpg",
    images: ["https://i.pinimg.com/736x/66/37/08/663708a0381ccb2c41064b20004aadd1.jpg"],
    inStock: true,
    stock: 22,
    featured: true,
    flavours: ["Honey", "Vanilla", "Oak"],
  },
  {
    id: 4,
    name: "Jack Daniel's Old No.7",
    brand: "Jack Daniel's",
    quantity: "1",
    category: "Whisky",
    subCategory: "Tennessee Whiskey",
    country: "USA",
    abv: "40%",
    volume: "750 ml",
    price: 2850,
    currency: "INR",
    rating: 4.8,
    reviewCount: 4200,
    description:
      "Smooth Tennessee whiskey with caramel, vanilla and toasted oak character.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPZ_g5cHNsnssIOLmoeYvx0MlLy3yqvp4NuYxdV5aDPrUuzI1b2hZxJ21p&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSPZ_g5cHNsnssIOLmoeYvx0MlLy3yqvp4NuYxdV5aDPrUuzI1b2hZxJ21p&s=10"],
    inStock: true,
    stock: 80,
    featured: true,
    flavours: ["Caramel", "Oak", "Vanilla"],
  },
  {
    id: 5,
    name: "Johnnie Walker Black Label",
    brand: "Johnnie Walker",
    quantity: "1",
    category: "Whisky",
    subCategory: "Blended Scotch",
    country: "Scotland",
    abv: "40%",
    volume: "750 ml",
    price: 3200,
    currency: "INR",
    rating: 4.8,
    reviewCount: 5100,
    description: "Blended Scotch whisky with smoky, fruity and spicy flavours.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5rzrdCyHiEU8H38kl8DUtQEowHVb94lYJUJROzkN1sw&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS5rzrdCyHiEU8H38kl8DUtQEowHVb94lYJUJROzkN1sw&s=10"],
    inStock: true,
    stock: 60,
    featured: true,
    flavours: ["Smoke", "Fruit", "Spice"],
  },
  {
    id: 6,
    name: "Rampur Indian Single Malt",
    brand: "Rampur",
    quantity: "1",
    category: "Whisky",
    subCategory: "Single Malt",
    country: "India",
    abv: "45%",
    volume: "750 ml",
    price: 5200,
    currency: "INR",
    rating: 4.7,
    reviewCount: 930,
    description:
      "Indian single malt with rich fruit, vanilla and gentle spice notes.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkBZaN3XANIaXVs31QMwj1Gy5iX0i1vZbZi1A3lj_Umw&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkBZaN3XANIaXVs31QMwj1Gy5iX0i1vZbZi1A3lj_Umw&s=10"],
    inStock: true,
    stock: 18,
    featured: true,
    flavours: ["Fruit", "Vanilla", "Spice"],
  },
  {
    id: 7,
    name: "Grey Goose Vodka",
    brand: "Grey Goose",
    quantity: "1",
    category: "Vodka",
    subCategory: "Premium Vodka",
    country: "France",
    abv: "40%",
    volume: "750 ml",
    price: 4800,
    currency: "INR",
    rating: 4.8,
    reviewCount: 2300,
    description:
      "Premium French vodka known for smooth texture and clean finish.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTrwBKzXi0oCzjeDK-p_eW9H7cIR-YvWgTqvR2EXb_Pw&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTrwBKzXi0oCzjeDK-p_eW9H7cIR-YvWgTqvR2EXb_Pw&s=10",
    ],
    inStock: true,
    stock: 40,
    featured: true,
    flavours: ["Clean", "Citrus", "Smooth"],
  },
  {
    id: 8,
    name: "Absolut Vodka",
    brand: "Absolut",
    quantity: "1",
    category: "Vodka",
    subCategory: "Swedish Vodka",
    country: "Sweden",
    abv: "40%",
    volume: "750 ml",
    price: 2100,
    currency: "INR",
    rating: 4.5,
    reviewCount: 3500,
    description: "Classic Swedish vodka with a smooth grain character.",
    thumbnail:
      "https://i.pinimg.com/1200x/da/8c/7e/da8c7edc20848132dc5550ef96ec01eb.jpg",
    images: [
      "https://i.pinimg.com/1200x/da/8c/7e/da8c7edc20848132dc5550ef96ec01eb.jpg",
    ],
    inStock: true,
    stock: 75,
    featured: false,
    flavours: ["Wheat", "Smooth", "Neutral"],
  },
  {
    id: 9,
    name: "Bombay Sapphire Gin",
    brand: "Bombay Sapphire",
    quantity: "1",
    category: "Gin",
    subCategory: "London Dry Gin",
    country: "England",
    abv: "40%",
    volume: "750 ml",
    price: 2600,
    currency: "INR",
    rating: 4.6,
    reviewCount: 1800,
    description:
      "Aromatic gin with botanical flavours and refreshing citrus notes.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ26NjCKgXbBYNBTJQ6SNwiKfUzrY0c_yUKS6fejfWnzQ&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ26NjCKgXbBYNBTJQ6SNwiKfUzrY0c_yUKS6fejfWnzQ&s=10"],
    inStock: true,
    stock: 55,
    featured: false,
    flavours: ["Juniper", "Citrus", "Herbs"],
  },
  {
    id: 10,
    name: "Stranger & Sons Gin",
    brand: "Stranger & Sons",
    quantity: "1",
    category: "Gin",
    subCategory: "Indian Craft Gin",
    country: "India",
    abv: "43%",
    volume: "700 ml",
    price: 3100,
    currency: "INR",
    rating: 4.7,
    reviewCount: 540,
    description:
      "Indian craft gin with citrus peel, spices and botanical richness.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbwDwunO-_VhXRX69mXcVwCoubSuKDxM79QDqkfQhiXw&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbwDwunO-_VhXRX69mXcVwCoubSuKDxM79QDqkfQhiXw&s=10"],
    inStock: true,
    stock: 25,
    featured: true,
    flavours: ["Citrus", "Pepper", "Botanical"],
  },
  {
    id: 11,
    name: "Bacardi Carta Blanca",
    brand: "Bacardi",
    quantity: "1",
    category: "Rum",
    subCategory: "White Rum",
    country: "Puerto Rico",
    abv: "40%",
    volume: "750 ml",
    price: 1600,
    currency: "INR",
    rating: 4.4,
    reviewCount: 1900,
    description: "Light white rum with subtle vanilla and almond notes.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHQqAM9bXIC1QQGEumo4TJVqg1ZRv7e-DF_Li4zHbzRw&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHQqAM9bXIC1QQGEumo4TJVqg1ZRv7e-DF_Li4zHbzRw&s=10"],
    inStock: true,
    stock: 90,
    featured: false,
    flavours: ["Vanilla", "Almond", "Sweet"],
  },
  {
    id: 12,
    name: "Captain Morgan Dark Rum",
    brand: "Captain Morgan",
    quantity: "1",
    category: "Rum",
    subCategory: "Dark Rum",
    country: "Jamaica",
    abv: "40%",
    volume: "750 ml",
    price: 1800,
    currency: "INR",
    rating: 4.5,
    reviewCount: 1500,
    description: "Dark rum with caramel sweetness and rich spice character.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz1oyNz7-SjjKA4yoJOQc1JD234XWYzb1i8yuO5u9x2Q&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTz1oyNz7-SjjKA4yoJOQc1JD234XWYzb1i8yuO5u9x2Q&s=10"],
    inStock: true,
    stock: 65,
    featured: false,
    flavours: ["Caramel", "Spice", "Molasses"],
  },
  {
    id: 13,
    name: "Corona Extra",
    brand: "Corona",
    quantity: "1",
    category: "Beer",
    subCategory: "Lager",
    country: "Mexico",
    abv: "4.5%",
    volume: "330 ml",
    price: 180,
    currency: "INR",
    rating: 4.6,
    reviewCount: 4300,
    description: "Light refreshing lager beer with crisp citrus notes.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpfF2AeHBORl0DVPeR18Rzq7H98UE62YrAu9A51fumJg&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpfF2AeHBORl0DVPeR18Rzq7H98UE62YrAu9A51fumJg&s=10",
    ],
    inStock: true,
    stock: 200,
    featured: false,
    flavours: ["Citrus", "Malt", "Light"],
  },
  {
    id: 14,
    name: "Budweiser Premium Lager",
    brand: "Budweiser",
    quantity: "1",
    category: "Beer",
    subCategory: "Lager",
    country: "USA",
    abv: "5%",
    volume: "500 ml",
    price: 220,
    currency: "INR",
    rating: 4.5,
    reviewCount: 5000,
    description: "Classic American lager with smooth malt flavour.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXpQt-mu7qC7ZT5hsNgupFflIrSMbL_H_3LlqUd164OA&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXpQt-mu7qC7ZT5hsNgupFflIrSMbL_H_3LlqUd164OA&s=10",
    ],
    inStock: true,
    stock: 300,
    featured: false,
    flavours: ["Malt", "Grain", "Crisp"],
  },
  {
    id: 15,
    name: "Heineken Original",
    brand: "Heineken",
    quantity: "1",
    category: "Beer",
    subCategory: "Premium Lager",
    country: "Netherlands",
    abv: "5%",
    volume: "650 ml",
    price: 220,
    currency: "INR",
    rating: 4.6,
    reviewCount: 3900,
    description:
      "International lager with balanced bitterness and refreshing malt character.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQG4eOmy4unjT3edCsJRniWIGXosm57sCuY6BtMAbaUg&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQG4eOmy4unjT3edCsJRniWIGXosm57sCuY6BtMAbaUg&s=10",
    ],
    inStock: true,
    stock: 150,
    featured: false,
    flavours: ["Malt", "Hops", "Crisp"],
  },
  {
    id: 16,
    name: "Kingfisher Ultra",
    brand: "Kingfisher",
    quantity: "1",
    category: "Beer",
    subCategory: "Premium Lager",
    country: "India",
    abv: "4.5%",
    volume: "650 ml",
    price: 180,
    currency: "INR",
    rating: 4.4,
    reviewCount: 6200,
    description: "Indian premium lager with light refreshing taste.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTReBd98VODuQHilJWEy1UFTf3zTEpGvU9B2oB6oqQIIA&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTReBd98VODuQHilJWEy1UFTf3zTEpGvU9B2oB6oqQIIA&s=10",
    ],
    inStock: true,
    stock: 250,
    featured: false,
    flavours: ["Light", "Malt", "Fresh"],
  },
  {
    id: 17,
    name: "Sula Brut",
    brand: "Sula",
    quantity: "1",
    category: "Wine",
    subCategory: "Sparkling Wine",
    country: "India",
    abv: "12%",
    volume: "750 ml",
    price: 1200,
    currency: "INR",
    rating: 4.5,
    reviewCount: 1200,
    description: "Indian sparkling wine with fruity and refreshing bubbles.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWtrcLMjzeobcR1QQ1cMr-WAjm83r16jKkuZBHtq738Q&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWtrcLMjzeobcR1QQ1cMr-WAjm83r16jKkuZBHtq738Q&s=10",
    ],
    inStock: true,
    stock: 40,
    featured: true,
    flavours: ["Apple", "Pear", "Citrus"],
  },
  {
    id: 18,
    name: "Grover Zampa La Reserve",
    brand: "Grover Zampa",
    quantity: "1",
    category: "Wine",
    subCategory: "Red Wine",
    country: "India",
    abv: "14%",
    volume: "750 ml",
    price: 1600,
    currency: "INR",
    rating: 4.6,
    reviewCount: 850,
    description:
      "Premium Indian red wine aged with rich berry and oak flavours.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM3u78wHbVAp6IV5mr2MCcq_LxG7V5ZtcWKfkEGfVoGA&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM3u78wHbVAp6IV5mr2MCcq_LxG7V5ZtcWKfkEGfVoGA&s=10",
    ],
    inStock: true,
    stock: 35,
    featured: false,
    flavours: ["Berry", "Oak", "Cherry"],
  },
  {
    id: 19,
    name: "Chivas Regal 12",
    brand: "Chivas Regal",
    quantity: "1",
    category: "Whisky",
    subCategory: "Blended Scotch",
    country: "Scotland",
    abv: "40%",
    volume: "750 ml",
    price: 4200,
    currency: "INR",
    rating: 4.7,
    reviewCount: 3800,
    description: "Smooth Scotch whisky with honey, vanilla and fruit notes.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhrBGcOC8spFTjawhhnzVIE6WlbR6g4Ti7o5riwAiH6A&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhrBGcOC8spFTjawhhnzVIE6WlbR6g4Ti7o5riwAiH6A&s=10"],
    inStock: true,
    stock: 50,
    featured: true,
    flavours: ["Honey", "Vanilla", "Fruit"],
  },
  {
    id: 20,
    name: "Ballantine's Finest",
    brand: "Ballantine's",
    quantity: "1",
    category: "Whisky",
    subCategory: "Blended Scotch",
    country: "Scotland",
    abv: "40%",
    volume: "750 ml",
    price: 2200,
    currency: "INR",
    rating: 4.5,
    reviewCount: 2100,
    description: "Classic blended Scotch with smooth vanilla and oak notes.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm98aik6bXQRV1w6zgrJH1LhrzQ_8xYnrmTTwjBbyy2A&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm98aik6bXQRV1w6zgrJH1LhrzQ_8xYnrmTTwjBbyy2A&s=10"],
    inStock: true,
    stock: 70,
    featured: false,
    flavours: ["Vanilla", "Oak", "Sweet"],
  },

  {
    id: 21,
    name: "Black Dog Triple Gold Reserve",
    brand: "Black Dog",
    quantity: "1",
    category: "Whisky",
    subCategory: "Blended Scotch",
    country: "Scotland",
    abv: "40%",
    volume: "750 ml",
    price: 2800,
    currency: "INR",
    rating: 4.5,
    reviewCount: 1700,
    description:
      "Smooth blended Scotch whisky with honey, malt and oak flavours.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcWDZVJxhG16BYFuxK3dEnJMGRyroIl4lN3jh0Fkmpdg&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTcWDZVJxhG16BYFuxK3dEnJMGRyroIl4lN3jh0Fkmpdg&s=10"],
    inStock: true,
    stock: 45,
    featured: false,
    flavours: ["Honey", "Malt", "Oak"],
  },
  {
    id: 22,
    name: "Teacher's Highland Cream",
    brand: "Teacher's",
    quantity: "1",
    category: "Whisky",
    subCategory: "Blended Scotch",
    country: "Scotland",
    abv: "40%",
    volume: "750 ml",
    price: 1900,
    currency: "INR",
    rating: 4.4,
    reviewCount: 1200,
    description: "Rich Scotch whisky with smoky malt and creamy texture.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRL0UR5CAug6iyCtruT9E4kxUX7XLxCZLczGKW_wXuQg_4LHzqhyLCKy4o&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRL0UR5CAug6iyCtruT9E4kxUX7XLxCZLczGKW_wXuQg_4LHzqhyLCKy4o&s=10"],
    inStock: true,
    stock: 80,
    featured: false,
    flavours: ["Smoke", "Malt", "Cream"],
  },
  {
    id: 23,
    name: "Monkey Shoulder",
    brand: "Monkey Shoulder",
    quantity: "1",
    category: "Whisky",
    subCategory: "Blended Malt",
    country: "Scotland",
    abv: "40%",
    volume: "700 ml",
    price: 3600,
    currency: "INR",
    rating: 4.7,
    reviewCount: 2500,
    description:
      "Modern blended malt whisky with vanilla and fruity sweetness.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQapwY_Gxir24FGrWDTDMc0uyVKtpuWOQ_rPLx2T3BEPA&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQapwY_Gxir24FGrWDTDMc0uyVKtpuWOQ_rPLx2T3BEPA&s=10"],
    inStock: true,
    stock: 35,
    featured: true,
    flavours: ["Vanilla", "Fruit", "Spice"],
  },
  {
    id: 24,
    name: "Glenfiddich 12 Year Old",
    brand: "Glenfiddich",
    quantity: "1",
    category: "Whisky",
    subCategory: "Single Malt Scotch",
    country: "Scotland",
    abv: "40%",
    volume: "750 ml",
    price: 5500,
    currency: "INR",
    rating: 4.8,
    reviewCount: 4600,
    description: "Classic Speyside single malt with pear and oak character.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4F1j4F7_TtFfTJjXcVhmPRdKMH8RIVNwgUBgYKFZIIg&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4F1j4F7_TtFfTJjXcVhmPRdKMH8RIVNwgUBgYKFZIIg&s=10"],
    inStock: true,
    stock: 25,
    featured: true,
    flavours: ["Pear", "Oak", "Honey"],
  },
  {
    id: 25,
    name: "The Glenlivet 12",
    brand: "The Glenlivet",
    quantity: "1",
    category: "Whisky",
    subCategory: "Single Malt Scotch",
    country: "Scotland",
    abv: "40%",
    volume: "750 ml",
    price: 5200,
    currency: "INR",
    rating: 4.7,
    reviewCount: 4100,
    description: "Smooth single malt with citrus, vanilla and floral notes.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6KIg-8TUgyL75yKVHoFhqZanHwm3PNWJV1ErbAJmefg&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6KIg-8TUgyL75yKVHoFhqZanHwm3PNWJV1ErbAJmefg&s=10"],
    inStock: true,
    stock: 28,
    featured: false,
    flavours: ["Citrus", "Vanilla", "Floral"],
  },
  {
    id: 26,
    name: "Smirnoff No.21 Vodka",
    brand: "Smirnoff",
    quantity: "1",
    category: "Vodka",
    subCategory: "Classic Vodka",
    country: "USA",
    abv: "40%",
    volume: "750 ml",
    price: 1500,
    currency: "INR",
    rating: 4.4,
    reviewCount: 3300,
    description: "Classic vodka with clean taste and smooth finish.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8LblqzAjhhcrQwd1JTHfyfnrcyDFlzTi62ifFILWYqKclzvH_Gd39hHQ&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8LblqzAjhhcrQwd1JTHfyfnrcyDFlzTi62ifFILWYqKclzvH_Gd39hHQ&s=10",
    ],
    inStock: true,
    stock: 100,
    featured: false,
    flavours: ["Clean", "Smooth", "Neutral"],
  },
  {
    id: 27,
    name: "Ketel One Vodka",
    brand: "Ketel One",
    quantity: "1",
    category: "Vodka",
    subCategory: "Premium Vodka",
    country: "Netherlands",
    abv: "40%",
    volume: "750 ml",
    price: 3500,
    currency: "INR",
    rating: 4.6,
    reviewCount: 1500,
    description: "Premium vodka distilled from wheat with a silky finish.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_q8rdGHxLaN0_ldLtJB0Bymki-J_Y5uwnc5s-mP691w&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_q8rdGHxLaN0_ldLtJB0Bymki-J_Y5uwnc5s-mP691w&s=10",
    ],
    inStock: true,
    stock: 32,
    featured: false,
    flavours: ["Wheat", "Silky", "Fresh"],
  },
  {
    id: 28,
    name: "Hendrick's Gin",
    brand: "Hendrick's",
    quantity: "1",
    category: "Gin",
    subCategory: "Premium Gin",
    country: "Scotland",
    abv: "41.4%",
    volume: "700 ml",
    price: 4200,
    currency: "INR",
    rating: 4.7,
    reviewCount: 2200,
    description: "Unique gin infused with cucumber and rose botanicals.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNgCq_IVMxJ5lEhVinonL7xKP4OacOGek0dJEIrhGl8Q&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNgCq_IVMxJ5lEhVinonL7xKP4OacOGek0dJEIrhGl8Q&s=10"],
    inStock: true,
    stock: 20,
    featured: true,
    flavours: ["Cucumber", "Rose", "Juniper"],
  },
  {
    id: 29,
    name: "Tanqueray London Dry Gin",
    brand: "Tanqueray",
    quantity: "1",
    category: "Gin",
    subCategory: "London Dry Gin",
    country: "England",
    abv: "43.1%",
    volume: "750 ml",
    price: 3000,
    currency: "INR",
    rating: 4.6,
    reviewCount: 1900,
    description: "Classic dry gin with bold juniper and citrus botanicals.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpiGKheBPberkyeZbfItnRFGAMs7j3PB0H1QlX3XSu9g&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpiGKheBPberkyeZbfItnRFGAMs7j3PB0H1QlX3XSu9g&s=10"],
    inStock: true,
    stock: 40,
    featured: false,
    flavours: ["Juniper", "Citrus", "Herbs"],
  },
  {
    id: 30,
    name: "Jose Cuervo Especial Tequila",
    brand: "Jose Cuervo",
    quantity: "1",
    category: "Tequila",
    subCategory: "Gold Tequila",
    country: "Mexico",
    abv: "40%",
    volume: "750 ml",
    price: 3200,
    currency: "INR",
    rating: 4.5,
    reviewCount: 1700,
    description: "Classic tequila with agave sweetness and warm spice notes.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwsBLB2jx1KgoADUQmuL4AGiWESxJeTaWcYqTVXKlBxQ&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwsBLB2jx1KgoADUQmuL4AGiWESxJeTaWcYqTVXKlBxQ&s=10",
    ],
    inStock: true,
    stock: 30,
    featured: false,
    flavours: ["Agave", "Spice", "Sweet"],
  },
  {
    id: 31,
    name: "Don Julio Blanco",
    brand: "Don Julio",
    quantity: "1",
    category: "Tequila",
    subCategory: "Blanco Tequila",
    country: "Mexico",
    abv: "40%",
    volume: "750 ml",
    price: 5200,
    currency: "INR",
    rating: 4.8,
    reviewCount: 2600,
    description: "Premium tequila with fresh agave, citrus and pepper notes.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTS0i-c5f2VD9Upw7LNvuXDlPppP89E3cQxDKmW0A86xw&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTS0i-c5f2VD9Upw7LNvuXDlPppP89E3cQxDKmW0A86xw&s=10",
    ],
    inStock: true,
    stock: 18,
    featured: true,
    flavours: ["Agave", "Citrus", "Pepper"],
  },
  {
    id: 32,
    name: "Havana Club 3 Years",
    brand: "Havana Club",
    quantity: "1",
    category: "Rum",
    subCategory: "White Rum",
    country: "Cuba",
    abv: "40%",
    volume: "750 ml",
    price: 1800,
    currency: "INR",
    rating: 4.5,
    reviewCount: 1300,
    description: "Cuban white rum aged for smooth cocktails and mixed drinks.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWR3ulut1uAE3KAmY0kpySrg78y3zt8k0y-emUB4XDVg&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWR3ulut1uAE3KAmY0kpySrg78y3zt8k0y-emUB4XDVg&s=10"],
    inStock: true,
    stock: 60,
    featured: false,
    flavours: ["Vanilla", "Sugarcane", "Light Spice"],
  },
  {
    id: 33,
    name: "Mount Gay Eclipse Rum",
    brand: "Mount Gay",
    quantity: "1",
    category: "Rum",
    subCategory: "Gold Rum",
    country: "Barbados",
    abv: "40%",
    volume: "750 ml",
    price: 2600,
    currency: "INR",
    rating: 4.6,
    reviewCount: 900,
    description: "Caribbean rum with banana, spice and toasted oak flavours.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeiYexShuJh7mi1a2IRbGhEFHXxSapr9zHFnNVq8gLZQ&s",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeiYexShuJh7mi1a2IRbGhEFHXxSapr9zHFnNVq8gLZQ&s"],
    inStock: true,
    stock: 35,
    featured: false,
    flavours: ["Banana", "Oak", "Spice"],
  },
  {
    id: 34,
    name: "Courvoisier VS Cognac",
    brand: "Courvoisier",
    quantity: "1",
    category: "Brandy",
    subCategory: "Cognac",
    country: "France",
    abv: "40%",
    volume: "700 ml",
    price: 6500,
    currency: "INR",
    rating: 4.7,
    reviewCount: 1200,
    description: "French cognac with fruity aroma and smooth oak finish.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeOrSDGGoCajpQ0slyl8O51DrutSlFxzIAo_6AmxSDUA&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeOrSDGGoCajpQ0slyl8O51DrutSlFxzIAo_6AmxSDUA&s=10",
    ],
    inStock: true,
    stock: 15,
    featured: true,
    flavours: ["Fruit", "Oak", "Caramel"],
  },
  {
    id: 35,
    name: "Hennessy VS Cognac",
    brand: "Hennessy",
    quantity: "1",
    category: "Brandy",
    subCategory: "Cognac",
    country: "France",
    abv: "40%",
    volume: "700 ml",
    price: 7200,
    currency: "INR",
    rating: 4.8,
    reviewCount: 3400,
    description: "World famous cognac with rich fruit and spice character.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnB0uTk5-a7oAu4iMdYyM3TbfDOqPefyPE2Vvo5wYqDw&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnB0uTk5-a7oAu4iMdYyM3TbfDOqPefyPE2Vvo5wYqDw&s=10",
    ],
    inStock: true,
    stock: 20,
    featured: true,
    flavours: ["Fruit", "Spice", "Oak"],
  },
  {
    id: 36,
    name: "Rémy Martin VSOP",
    brand: "Rémy Martin",
    quantity: "1",
    category: "Brandy",
    subCategory: "Cognac",
    country: "France",
    abv: "40%",
    volume: "700 ml",
    price: 8500,
    currency: "INR",
    rating: 4.8,
    reviewCount: 2100,
    description: "Elegant cognac with vanilla, dried fruit and spice notes.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQOWCN3YOwnCJ-bHz9r-W7zA6S_DccEPTZSV4B_K2zsOM29Hnlcusem3U&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQOWCN3YOwnCJ-bHz9r-W7zA6S_DccEPTZSV4B_K2zsOM29Hnlcusem3U&s=10",
    ],
    inStock: true,
    stock: 12,
    featured: false,
    flavours: ["Vanilla", "Fruit", "Spice"],
  },
  {
    id: 37,
    name: "Baileys Original Irish Cream",
    brand: "Baileys",
    quantity: "1",
    category: "Liqueur",
    subCategory: "Cream Liqueur",
    country: "Ireland",
    abv: "17%",
    volume: "750 ml",
    price: 2800,
    currency: "INR",
    rating: 4.7,
    reviewCount: 2900,
    description: "Creamy Irish liqueur with chocolate and coffee flavours.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLw5qRhsP2c8FFj07hTE6ZBaAdY_BTjgORfz6adGz3BQ&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLw5qRhsP2c8FFj07hTE6ZBaAdY_BTjgORfz6adGz3BQ&s=10"],
    inStock: true,
    stock: 45,
    featured: false,
    flavours: ["Chocolate", "Coffee", "Cream"],
  },
  {
    id: 38,
    name: "Jägermeister",
    brand: "Jägermeister",
    quantity: "1",
    category: "Liqueur",
    subCategory: "Herbal Liqueur",
    country: "Germany",
    abv: "35%",
    volume: "700 ml",
    price: 2600,
    currency: "INR",
    rating: 4.6,
    reviewCount: 3000,
    description: "German herbal liqueur made with botanicals and spices.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfw3au7IS0KICF6MrsMsQZ000EUBlmiA4Bv51iEEO7rg&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfw3au7IS0KICF6MrsMsQZ000EUBlmiA4Bv51iEEO7rg&s=10"],
    inStock: true,
    stock: 38,
    featured: false,
    flavours: ["Herbs", "Spice", "Sweet"],
  },
  {
    id: 39,
    name: "Campari",
    brand: "Campari",
    quantity: "1",
    category: "Liqueur",
    subCategory: "Aperitif",
    country: "Italy",
    abv: "25%",
    volume: "750 ml",
    price: 2400,
    currency: "INR",
    rating: 4.5,
    reviewCount: 1400,
    description: "Italian bitter aperitif with citrus and herbal notes.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwoJk812NP60oxP-AxlEXNyBNN2ox1wNudCiLEK1T12g&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwoJk812NP60oxP-AxlEXNyBNN2ox1wNudCiLEK1T12g&s=10"],
    inStock: true,
    stock: 30,
    featured: false,
    flavours: ["Orange", "Herbs", "Bitter"],
  },
  {
    id: 40,
    name: "Aperol",
    brand: "Aperol",
    quantity: "1",
    category: "Liqueur",
    subCategory: "Aperitif",
    country: "Italy",
    abv: "11%",
    volume: "700 ml",
    price: 2200,
    currency: "INR",
    rating: 4.6,
    reviewCount: 1800,
    description: "Bright Italian aperitif with orange and herbal flavours.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsRRxs9sGfEAgqrBBuTqppJkdpoSItfldmCD8JUHluTQ&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsRRxs9sGfEAgqrBBuTqppJkdpoSItfldmCD8JUHluTQ&s=10"],
    inStock: true,
    stock: 55,
    featured: false,
    flavours: ["Orange", "Herbs", "Sweet"],
  },
  {
    id: 41,
    name: "Indri Trini Single Malt",
    brand: "Indri",
    quantity: "1",
    category: "Whisky",
    subCategory: "Indian Single Malt",
    country: "India",
    abv: "46%",
    volume: "750 ml",
    price: 3800,
    currency: "INR",
    rating: 4.7,
    reviewCount: 760,
    description:
      "Indian single malt whisky with smoky, fruity and spicy character.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVUFgeTIS8K23S7rorv76zU3w00Lqn1AtVGSV4pxn6VTXZcONPBkp3ngY&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVUFgeTIS8K23S7rorv76zU3w00Lqn1AtVGSV4pxn6VTXZcONPBkp3ngY&s=10"],
    inStock: true,
    stock: 22,
    featured: true,
    flavours: ["Smoke", "Fruit", "Spice"],
  },
  {
    id: 42,
    name: "McDowell's No.1 Whisky",
    brand: "McDowell's",
    quantity: "1",
    category: "Whisky",
    subCategory: "Indian Whisky",
    country: "India",
    abv: "42.8%",
    volume: "750 ml",
    price: 900,
    currency: "INR",
    rating: 4.2,
    reviewCount: 5400,
    description: "Popular Indian whisky with smooth grain and caramel notes.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsfTWvodpMaUlk-Pq5fUMNWfmn5PjYzt--WNCiE2mm2A&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsfTWvodpMaUlk-Pq5fUMNWfmn5PjYzt--WNCiE2mm2A&s=10"],
    inStock: true,
    stock: 180,
    featured: false,
    flavours: ["Caramel", "Grain", "Sweet"],
  },
  {
    id: 43,
    name: "Blenders Pride Reserve Collection",
    brand: "Blenders Pride",
    quantity: "1",
    category: "Whisky",
    subCategory: "Indian Premium Whisky",
    country: "India",
    abv: "42.8%",
    volume: "750 ml",
    price: 1400,
    currency: "INR",
    rating: 4.4,
    reviewCount: 3200,
    description: "Premium Indian whisky with smooth oak and vanilla finish.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw08Ed_fD1AyEN-grGB9vtASGvDt7KPzMgW_X_PfhT7XIyyvOCYd5mEi4&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQw08Ed_fD1AyEN-grGB9vtASGvDt7KPzMgW_X_PfhT7XIyyvOCYd5mEi4&s=10"],
    inStock: true,
    stock: 95,
    featured: false,
    flavours: ["Oak", "Vanilla", "Spice"],
  },
  {
    id: 44,
    name: "Royal Challenge United Spirit",
    brand: "Royal Challenge",
    quantity: "1",
    category: "Whisky",
    subCategory: "Indian Whisky",
    country: "India",
    abv: "42.8%",
    volume: "750 ml",
    price: 1100,
    currency: "INR",
    rating: 4.3,
    reviewCount: 2900,
    description: "Indian blended whisky with balanced malt flavour.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRd_DfoCdcnaXi5pWNjYlXIdqqd5Z_dOZrYc_n7mB7-rA&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRd_DfoCdcnaXi5pWNjYlXIdqqd5Z_dOZrYc_n7mB7-rA&s=10"],
    inStock: true,
    stock: 120,
    featured: false,
    flavours: ["Malt", "Oak", "Smooth"],
  },
  {
    id: 45,
    name: "Antiquity Blue",
    brand: "Antiquity",
    quantity: "1",
    category: "Whisky",
    subCategory: "Indian Premium Whisky",
    country: "India",
    abv: "42.8%",
    volume: "750 ml",
    price: 1300,
    currency: "INR",
    rating: 4.4,
    reviewCount: 2400,
    description: "Classic Indian whisky with rich aroma and smooth finish.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwdQI_7pECstVhV-oYe_JYSFT3rRltsOfhb54Vylx3qg&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwdQI_7pECstVhV-oYe_JYSFT3rRltsOfhb54Vylx3qg&s=10"],
    inStock: true,
    stock: 85,
    featured: false,
    flavours: ["Oak", "Spice", "Malt"],
  },
  {
    id: 46,
    name: "Magic Moments Vodka",
    brand: "Magic Moments",
    quantity: "1",
    category: "Vodka",
    subCategory: "Indian Vodka",
    country: "India",
    abv: "42.8%",
    volume: "750 ml",
    price: 900,
    currency: "INR",
    rating: 4.3,
    reviewCount: 4000,
    description: "Indian vodka with smooth grain character.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAwVZfvHBdliyZrH_1I60DjNI8pKfsONQX8fY57oNQYTQA-omjj_TpouI&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAwVZfvHBdliyZrH_1I60DjNI8pKfsONQX8fY57oNQYTQA-omjj_TpouI&s=10",
    ],
    inStock: true,
    stock: 140,
    featured: false,
    flavours: ["Grain", "Smooth", "Clean"],
  },
  {
    id: 47,
    name: "White Mischief Vodka",
    brand: "White Mischief",
    quantity: "1",
    category: "Vodka",
    subCategory: "Indian Vodka",
    country: "India",
    abv: "42.8%",
    volume: "750 ml",
    price: 850,
    currency: "INR",
    rating: 4.2,
    reviewCount: 2100,
    description: "Affordable Indian vodka with a clean refreshing profile.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzRXG1HXgnslqImFk32Y8wTxDXP20hxqvoDRBi0E4wug&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzRXG1HXgnslqImFk32Y8wTxDXP20hxqvoDRBi0E4wug&s=10",
    ],
    inStock: true,
    stock: 110,
    featured: false,
    flavours: ["Clean", "Light", "Neutral"],
  },
  {
    id: 48,
    name: "Greater Than Gin",
    brand: "Greater Than",
    quantity: "1",
    category: "Gin",
    subCategory: "Indian Craft Gin",
    country: "India",
    abv: "45%",
    volume: "750 ml",
    price: 1500,
    currency: "INR",
    rating: 4.5,
    reviewCount: 900,
    description: "Indian craft gin with citrus and juniper botanicals.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2fP8PvdVCS0CUaumnn-ksPcT1lWbmCDMW23JdcbaNiA&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2fP8PvdVCS0CUaumnn-ksPcT1lWbmCDMW23JdcbaNiA&s=10"],
    inStock: true,
    stock: 35,
    featured: true,
    flavours: ["Juniper", "Citrus", "Spice"],
  },
  {
    id: 49,
    name: "Hapusa Himalayan Dry Gin",
    brand: "Hapusa",
    quantity: "1",
    category: "Gin",
    subCategory: "Craft Gin",
    country: "India",
    abv: "43%",
    volume: "750 ml",
    price: 3200,
    currency: "INR",
    rating: 4.7,
    reviewCount: 450,
    description: "Indian gin inspired by Himalayan botanicals.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWLTiv0HPEBqNlvaDXtofkdr8OaRpaiPra1SJv5XABHelpkZ3vmOdkY5A&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWLTiv0HPEBqNlvaDXtofkdr8OaRpaiPra1SJv5XABHelpkZ3vmOdkY5A&s=10"],
    inStock: true,
    stock: 18,
    featured: true,
    flavours: ["Juniper", "Earthy", "Herbs"],
  },
  {
    id: 50,
    name: "Sula Chenin Blanc",
    brand: "Sula",
    quantity: "1",
    category: "Wine",
    subCategory: "White Wine",
    country: "India",
    abv: "13%",
    volume: "750 ml",
    price: 950,
    currency: "INR",
    rating: 4.4,
    reviewCount: 1500,
    description: "Refreshing Indian white wine with tropical fruit notes.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiVPYFJoA1LN26nYuHD7mLKLGy1ICjdahFvduAYGCGJg&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiVPYFJoA1LN26nYuHD7mLKLGy1ICjdahFvduAYGCGJg&s=10",
    ],
    inStock: true,
    stock: 70,
    featured: false,
    flavours: ["Apple", "Tropical Fruit", "Citrus"],
  },
  {
    id: 51,
    name: "Carlsberg Smooth",
    brand: "Carlsberg",
    quantity: "1",
    category: "Beer",
    subCategory: "Lager",
    country: "Denmark",
    abv: "5%",
    volume: "650 ml",
    price: 190,
    currency: "INR",
    rating: 4.4,
    reviewCount: 3200,
    description: "Smooth Danish lager with balanced malt and hop bitterness.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYMOotmnJRFlNSlYXdpg7-53zuzRqMzgZL4pBUV_fMWw&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYMOotmnJRFlNSlYXdpg7-53zuzRqMzgZL4pBUV_fMWw&s=10",
    ],
    inStock: true,
    stock: 180,
    featured: false,
    flavours: ["Malt", "Hops", "Crisp"],
  },
  {
    id: 52,
    name: "Tuborg Green",
    brand: "Tuborg",
    quantity: "1",
    category: "Beer",
    subCategory: "Lager",
    country: "Denmark",
    abv: "4.6%",
    volume: "650 ml",
    price: 160,
    currency: "INR",
    rating: 4.3,
    reviewCount: 4100,
    description: "Light refreshing lager with mild bitterness.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5ryucySLEXlK_2L9lexDfIw-U6njWBXVt-83nV5Q8sg&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5ryucySLEXlK_2L9lexDfIw-U6njWBXVt-83nV5Q8sg&s=10",
    ],
    inStock: true,
    stock: 220,
    featured: false,
    flavours: ["Light", "Malt", "Fresh"],
  },
  {
    id: 53,
    name: "Bira 91 Blonde",
    brand: "Bira 91",
    quantity: "1",
    category: "Beer",
    subCategory: "Craft Lager",
    country: "India",
    abv: "4.7%",
    volume: "330 ml",
    price: 150,
    currency: "INR",
    rating: 4.5,
    reviewCount: 2500,
    description: "Indian craft beer with smooth wheat and citrus notes.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRl0An3GoKa3g0-6B6YfBYajpA-Zty-dMT7yIs1mo8bmA&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRl0An3GoKa3g0-6B6YfBYajpA-Zty-dMT7yIs1mo8bmA&s=10",
    ],
    inStock: true,
    stock: 130,
    featured: true,
    flavours: ["Wheat", "Citrus", "Malt"],
  },
  {
    id: 54,
    name: "Bira 91 White",
    brand: "Bira 91",
    quantity: "1",
    category: "Beer",
    subCategory: "Wheat Beer",
    country: "India",
    abv: "4.7%",
    volume: "330 ml",
    price: 160,
    currency: "INR",
    rating: 4.6,
    reviewCount: 2800,
    description: "Cloudy wheat beer with citrus and coriander character.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBbpx7avWzSOxVz_GGNsixWcfFGFXKFHRz1HFvaud4Eg&s",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBbpx7avWzSOxVz_GGNsixWcfFGFXKFHRz1HFvaud4Eg&s",
    ],
    inStock: true,
    stock: 100,
    featured: true,
    flavours: ["Citrus", "Wheat", "Spice"],
  },
  {
    id: 55,
    name: "Hoegaarden Witbier",
    brand: "Hoegaarden",
    quantity: "1",
    category: "Beer",
    subCategory: "Belgian Wheat Beer",
    country: "Belgium",
    abv: "4.9%",
    volume: "330 ml",
    price: 250,
    currency: "INR",
    rating: 4.7,
    reviewCount: 2100,
    description: "Belgian wheat beer with orange peel and coriander flavours.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxVlk-vnVgTwv7x2Ec3KbYr3m-4pGgow3HOmLSBPZC4A&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxVlk-vnVgTwv7x2Ec3KbYr3m-4pGgow3HOmLSBPZC4A&s=10",
    ],
    inStock: true,
    stock: 80,
    featured: false,
    flavours: ["Orange", "Coriander", "Wheat"],
  },
  {
    id: 56,
    name: "Stella Artois",
    brand: "Stella Artois",
    quantity: "1",
    category: "Beer",
    subCategory: "Belgian Lager",
    country: "Belgium",
    abv: "5%",
    volume: "330 ml",
    price: 240,
    currency: "INR",
    rating: 4.6,
    reviewCount: 3000,
    description: "Premium Belgian lager with crisp malt flavour.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgGSioMGIMXJVNaW-1eO8zJit1cT8TQeGQSi9veRsqNw&s=10",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgGSioMGIMXJVNaW-1eO8zJit1cT8TQeGQSi9veRsqNw&s=10",
    ],
    inStock: true,
    stock: 75,
    featured: false,
    flavours: ["Malt", "Hops", "Crisp"],
  },
  {
    id: 57,
    name: "Kingfisher Strong",
    brand: "Kingfisher",
    quantity: "1",
    category: "Beer",
    subCategory: "Strong Lager",
    country: "India",
    abv: "8%",
    volume: "650 ml",
    price: 180,
    currency: "INR",
    rating: 4.3,
    reviewCount: 7000,
    description: "Strong Indian lager with bold malt character.",
    thumbnail:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvSF8LWESrNE-CNgwUOn02d8-WUQA1AFCHquyVc0bIow&s",
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvSF8LWESrNE-CNgwUOn02d8-WUQA1AFCHquyVc0bIow&s",
    ],
    inStock: true,
    stock: 300,
    featured: false,
    flavours: ["Malt", "Strong", "Sweet"],
  },
  {
    id: 58,
    name: "Red Bull Energy Drink",
    brand: "Red Bull",
    quantity: "1",
    category: "Soft Drink",
    subCategory: "Energy Drink",
    country: "Austria",
    abv: "0%",
    volume: "250 ml",
    price: 125,
    currency: "INR",
    rating: 4.7,
    reviewCount: 8000,
    description: "Energy drink with caffeine, taurine and refreshing flavour.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtlqZJK-KCB-K8TGpxKgjylnomupW4AoGb_yBolXZnleEN1sOW8EUADZQ&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtlqZJK-KCB-K8TGpxKgjylnomupW4AoGb_yBolXZnleEN1sOW8EUADZQ&s=10"],
    inStock: true,
    stock: 500,
    featured: false,
    flavours: ["Citrus", "Sweet", "Energy"],
  },
  {
    id: 59,
    name: "Coca Cola Classic",
    brand: "Coca Cola",
    quantity: "1",
    category: "Soft Drink",
    subCategory: "Cola",
    country: "USA",
    abv: "0%",
    volume: "750 ml",
    price: 45,
    currency: "INR",
    rating: 4.8,
    reviewCount: 12000,
    description: "Classic cola beverage with caramel sweetness.",
    thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXrCjWb_mWdYI-wwv7v-xpNi5cjMc2741qxFiijFFqJA&s=10",
    images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXrCjWb_mWdYI-wwv7v-xpNi5cjMc2741qxFiijFFqJA&s=10"],
    inStock: true,
    stock: 1000,
    featured: false,
    flavours: ["Cola", "Caramel", "Sweet"],
  },
  {
    id: 60,
    name: "Schweppes Tonic Water",
    brand: "Schweppes",
    quantity: "1",
    category: "Soft Drink",
    subCategory: "Mixer",
    country: "Switzerland",
    abv: "0%",
    volume: "300 ml",
    price: 60,
    currency: "INR",
    rating: 4.5,
    reviewCount: 2600,
    description: "Classic tonic water with refreshing quinine bitterness.",
    thumbnail: "https://i.pinimg.com/236x/33/96/15/339615424342f9e171e300ac31731a1c.jpg",
    images: ["https://i.pinimg.com/236x/33/96/15/339615424342f9e171e300ac31731a1c.jpg"],
    inStock: true,
    stock: 250,
    featured: false,
    flavours: ["Quinine", "Citrus", "Bitter"],
  },
];

export default products;
